### ISSUE TITLE
Keep tracking Community banned account..

### ISSUE THREAD

**Issue by pelasta** [IceQ1337/SteamBanChecker_Discord#10]
the BOT stops tracking players who are community banned, I think it should keep tracking them until they get a game ban or VAC.

the reason why, I have some players who are community banned, and a week later they got a game ban and I only got notified about the community ban when the most important is the game/vac bans.

hopefully, you can make the bot keep tracking accounts who are community banned.

thanks!

**Comment by IceQ1337** [comment]
Hello @pelasta 
I've double checked, tested it locally and the bot is working as intended. A profile is still being tracked after getting community banned and ist not removed from the list. If you experience this issue again, please check `datastore/profiles.db` after a community ban by opening the file with an editor like notepad and search for the SteamID. You will see if `CommunityBanned` is set to true and if `Tracked` is still set to true. If its set to false and the profile is not game or VAC banned, please reply to this issue again.
