### ISSUE TITLE
0 response back via discord

### ISSUE THREAD

**Issue by Bobby8904** [IceQ1337/SteamBanChecker_Discord#16]
Hi there so i am having an issue I set up everything but now when I add a user with /add "steamid64" 
No response comes from the bot and nothing gets stored is it because I am using a vaced steam account's API? 
Or what could it be?

**Comment by IceQ1337** [comment]
If you haven't changed it in the config, the default command prefix is "!".
Try using `!add steamid64` instead

**Comment by Bobby8904** [comment]
Ahh i see my bad saw it said / somewhere ok so i added the access role in cfg by copying a specific role id and saved it in the cfg and now when I type the right prefix and all bot says you don't have perms even when I remove it all

**Comment by Bobby8904** [comment]
All good managed to make it work all it needed was a restart my last questions is the following for the output in config if I leave that blank will it send it to the same channel being input or will it dm people directly also if I make another channel output it will send banned users there when they get banned correct?

**Comment by IceQ1337** [comment]
Yes, if you leave the output field empty, it will send responses to all specified input channels and you can specify a different output channel if you want to seperate input and output. The bot will never message any users via private message.
