### ISSUE TITLE
You don't have permissions to use this command!

### ISSUE THREAD

**Issue by Bobby8904** [IceQ1337/SteamBanChecker_Discord#17]
So when i add the role's id to the config it looks like this **"accessRole": "7836648995464654654"** and when I assign myself the role it doesn't seem to work and spits out **You don't have permissions to use this command!**

**Comment by Bobby8904** [comment]
Do i add the name of the role or the id as shown above?

**Comment by IceQ1337** [comment]
You will need to use the role name instead of the ID.

**Comment by Bobby8904** [comment]
cool thanks for the fast response <3
