### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Nasri69** [IceQ1337/SteamBanChecker_Discord#4]
Hi,
Is there any chance to add griefing ban notifications? I found something like that maybe it will help you (https://github.com/KillaBoi/Steam-CSGO-Griefing-Bans/blob/master/example.php)

**Comment by IceQ1337** [comment]
There is no way to outright identify a griefing ban. The script you linked basically just takes a very inaccurate guess by comparing the profile data to the API data. This script will already report griefing bans, if they are applied to the API data as VAC or game bans.
