### ISSUE TITLE
getStats > TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by guiiicd** [IceQ1337/SteamBanChecker_Discord#8]
I'm hosting the bot in glitch, but you are giving this error `[ERROR] [Database] getStats > TypeError: fields.flat is not a function` when I give the stats command, I would like to know if you know what can help me solve this?
![Screenshot_1](https://user-images.githubusercontent.com/24928611/98562150-19dcef80-2280-11eb-9072-08a9d7863f74.png)

**Comment by IceQ1337** [comment]
Hello @FPSGuilherme 
What version of Node.js are you running? Please make sure you are using the latest LTS (14) or at least version 12. That will most-likely solve your issue.

**Comment by guiiicd** [comment]
Actually, I hadn't checked the node version, thanks a lot, it's working!
