### ISSUE TITLE
Remove channel restriction

### ISSUE THREAD

**Issue by guiiicd** [IceQ1337/SteamBanChecker_Discord#9]
Hello again hahaha, I would like to know if you have any way to remove the restriction on which channel I can send command to bot (botChannelInput), because I wanted to use the bot on my server and on that of some friends.

**Comment by IceQ1337** [comment]
Hello @FPSGuilherme 
As described in the configuration instructions, `botChannelInput` can be an array of multiple channels.  

Example: ["ID1", "ID2"]

**Comment by guiiicd** [comment]
Like this? You're making a mistake
![image](https://user-images.githubusercontent.com/24928611/98609398-8d542080-22c3-11eb-8faa-3ba61ef3d25e.png)
@IceQ1337

**Comment by IceQ1337** [comment]
The configuration value has to be the array itself and should look like this: `"botChannelInput": ["12345", "56789"],`
